language: java
matrix:
  include:
    - os: osx
      # jdk 8
      osx_image: xcode9.3
    - os: osx
      # jdk 10
      osx_image: xcode10
    - os: osx
      # jdk 11
      osx_image: xcode10.2
install: true
script:
  - java -version
  - ./gradlew --version
  - ./gradlew clean build --stacktrace --warning-mode all -DenabledModules="common,library:example,application:jvm:jvm8:terminal,application:jvm:jvm8:api:spring_boot,application:js:vanilla,application:native:apple:iosApp"
