matrix:
  include:
    - language: java
      os: osx
      osx_image: xcode11.3
      env:
        - BUILD_CI=TRAVIS
        - BUILD_OS=MAC_OS
        - BASH_ENV=~/.bashrc
        - ANDROID_HOME=$HOME/android-sdk
        - GRADLE_OPTS="-Xmx3048m -Xms3048m"
      before_install:
        - ./resources/scripts/ci/prepare.sh
      install: true
      script:
        - ./resources/scripts/complete_run.sh
  allow_failures:
    env: ALLOW_FAILURE=true
