matrix:
  include:
    - language: java
      os: osx
      osx_image: xcode11.3
      env:
        - BUILD_CI=TRAVIS
        - BUILD_OS=MAC_OS
        - BASH_ENV=~/.bashrc
        - ANDROID_HOME=$HOME/Library/Android/sdk
        - GRADLE_OPTS="-Xmx3048m -Xms3048m"
      before_install:
        - ./resources/scripts/ci/prepare.sh
        - source "$HOME/.sdkman/bin/sdkman-init.sh" # Without this line Travis do not get the correct Java version
        - ./resources/scripts/ci/show_relevant_information.sh
      install: true
      script:
        - ./resources/scripts/complete_run.sh
  allow_failures:
    env: ALLOW_FAILURE=true
