image:
  - Visual Studio 2017
environment:
    BASH_ENV: ~/.bashrc
    BUILD_CI: APPVEYOR
    BUILD_OS: WINDOWS
    ANDROID_HOME: "%ProgramFiles(x86)%\\Android\\android-sdk"
    GRADLE_OPTS: "-Xmx3048m -Xms3048m"
install:
  - ps: $env:Path = "%ProgramFiles%\Git\bin;$env:Path"
  - bash resources/scripts/ci/install_package_manager_and_common_packages.sh
#  - bash resources/scripts/ci/install_java.sh
#  - resources/scripts/ci/install_android_sdk.bat
#  - bash resources/scripts/ci/show_relevant_information.sh
#build_script:
#  - bash resources/scripts/complete_run.sh
