version: 2
jobs:
  jdk8:
    docker:
      - image: openjdk:8-jdk
      - image: circleci/openjdk:8-jdk-node-browsers
    environment:
      BUILD_CI: CIRCLE_CI
      BUILD_OS: LINUX
      BASH_ENV: ~/.bashrc
      ANDROID_HOME: /root/android-sdk
      GRADLE_OPTS: -Xmx3048m -Xms3048m
    steps:
      - checkout
      - run: ./resources/scripts/ci/prepare.sh
      - run: ./resources/scripts/complete_run.sh
workflows:
  version: 2
  all:
    jobs:
      - jdk8
